{{- if $.Values.global.agtK8Config.stsName -}}
{{- $agtMode := include "agent.mode" . -}}
{{- if or (eq $agtMode "gateway") (.Values.global.agtK8Config.withIngress.enabled) -}}
{{- $fullName := include "agentlber.fullname" . -}}
{{- $svcPort := .Values.agtK8Config.svcPortNum -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "agentlber.labels" . | nindent 4 }}
  annotations:
    {}
spec:
  {{- include "agentlber.ingress" . | nindent 2 }}
{{- end }}
{{- end }}