apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentlber.fullname" . }}
  labels:
    {{- include "agentlber.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- include "agentlber.svcPortSpec" . | nindent 4 }}
    {{- include "agentlber.svcHealthPortSpec" . | nindent 4 }}
  selector:
    {{- include "agentlber.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.agtK8Config.stsName }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    {{- include "agent.svcPortSpec" . | nindent 4 }}
    {{- include "agent.svcHealthPortSpec" . | nindent 4 }}
  selector:
    {{- include "agent.selectorLabels" . | nindent 4 }}