language: minimal
if: head_branch =~ ^v1beta_qa_oci_spec_update$ OR branch = v1beta_qa_oci_spec_update_ft

services:
  - docker
  
before_install:

script:
   - cd ./spec/qa && docker build -t enterpriseconnect/qa-ft:v1beta . && cd -
   
deploy:
  - provider: script
    skip_cleanup: true
    script: >-
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
      docker push enterpriseconnect/qa-ft:v1beta
    on:
      branch: v1beta_oci_spec

after_deploy: >-
  docker rmi enterpriseconnect/qa-ft:v1beta -f
  ls -al
notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    on_success: always  
    on_failure: always
