# author: apolo.yasuda@ge.com

language: minimal
if: head_branch =~ ^v1.1beta_helm_pkg_update$ OR branch = v1.1beta_helm_pkg

services:
  - docker

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config
    # helm chart version
    - AGENT_CHART_REV=0.1.4
    - AGENT_HELPER_CHART_REV=0.1.3
    - AGENT_PLG_CHART_REV=0.1.3

before_install:
- sudo apt-get -qq -y install conntrack

before_script:
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
  - chmod 775 ./spec-sim.sh ./docker-deployment-sim.sh ./k8s-deployment-sim.sh ./argocd-deployment-sim.sh ./minikube-bootstrap.sh

script:
  # move docker spec test to oci spec
  #- source ./docker-deployment-sim.sh
  #- source ./minikube-bootstrap.sh
  - source ./spec-sim.sh
  #- source ./k8s-deployment-sim.sh
  #- source ./argocd-deployment-sim.sh
  
after_deploy: chmod 775 ./after_deploy.sh && ./after_deploy.sh

deploy:
  provider: pages 
  github_token: $GITHUB_TOKEN
  local_dir: k8s/pkg
  target_branch: disty
  verbose: true
  skip_cleanup: true
  keep_history: true
  on:
    branch: v1.1beta_helm_pkg

notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    #- enterprise-connect@ge.com
    on_success: always  
    on_failure: always
