language: minimal
if: head_branch = v1beta_oci_spec_update OR branch = v1beta_oci_spec

services:
  - docker
  
before_install:

script:
   - cd ./spec/agent && docker build -t enterpriseconnect/agent:v1beta --build-arg EC_REV_V1BETA=${EC_REV_V1BETA} . && cd -
   - cd ./spec/plugin && docker build -t enterpriseconnect/plugins:v1beta --build-arg EC_REV_V1BETA=${EC_REV_V1BETA} . && cd -
   - cd ./spec/build && docker build -t enterpriseconnect/build:v1beta --build-arg EC_REV_V1BETA=${EC_REV_V1BETA} . && cd -
   
deploy:
  - provider: script
    skip_cleanup: true
    script: >-
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
      docker push enterpriseconnect/agent:v1beta && 
      docker push enterpriseconnect/plugins:v1beta &&
      docker push enterpriseconnect/build:v1beta
    on:
      branch: v1beta_oci_spec

after_deploy: >-
  docker rmi enterpriseconnect/agent:v1beta -f && docker run -it enterpriseconnect/agent:v1beta agent -ver &&
  docker rmi enterpriseconnect/plugins:v1beta -f && docker run -it enterpriseconnect/plugins:v1beta agent -inf &&
  docker rmi enterpriseconnect/build:v1beta -f && docker run -it enterpriseconnect/build:v1beta go version &&
  ls -al
notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    #- enterprise-connect@ge.com
    on_success: always  
    on_failure: always
