language: minimal
if: head_branch =~ ^v1beta_oci_spec_update$ OR branch = v1beta_oci_spec

services:
  - docker
  
before_install:

script:
   - cd ./spec/agent && docker build -t enterpriseconnect/agent:v1beta --build-arg EC_REV_V1BETA=${EC_REV_V1BETA} .
   - bash <(curl -s https://enterprise-connect.github.io/oci/k8s/conf.txt) -ver
   - git log -5
   - git rev-parse HEAD
   
deploy:
  - provider: script
    skip_cleanup: true
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push enterpriseconnect/agent:v1beta
    on:
      branch: v1beta_oci_spec

after_deploy: docker rmi enterpriseconnect/agent:v1beta -f && docker run -it enterpriseconnect/agent:v1beta ./agent -ver

notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    - prasad.alokam@ge.com
    - Simran.Choudhary@ge.com
    - Sheshank.Gujjari@ge.com
    on_success: always  
    on_failure: always
