language: minimal
if: head_branch =~ ^v1beta_svc_oci_spec_update$ OR branch = v1beta_svc_oci_spec

services:
  - docker  

env:
  global:
    - SERVICE_BRANCH=v1beta
    - ENV=v1beta.sendai.1080
    - EC_REV=v1beta
    - ADMIN_USR=admin
    - ZAC_UAA=https://predix-uaa.run.aws-usw02-dev.ice.predix.io/oauth/token
    - ZAC_URL=https://predix-zac.run.aws-usw02-dev.ice.predix.io/v1/authorization/
    - ZAC_SERVICE_ID=enterprise-connect
    - NUREGO_FEATURE_ID=api_calls
    - NUREGO_TKN_INS=ins_01b6-765e-446e-b0e5-d958ac2afb72
    - NUREGO_USAGE_FEATURE_ID=data_usage
    - NUREGO_ENDPOINT=https://am-staging.nurego.com/v1
    - NUREGO_TKN_URL=https://am-staging.nurego.com/v1/auth/token

script:
  - wget https://raw.githubusercontent.com/EC-Release/auth-api/v1beta/dist/api/api_linux.tar.gz
  - tar -xzvf api_linux.tar.gz
  - cp ./api_linux ./spec/service
  - cd ./spec/service
  - git clone https://${TOKEN_NAME}:${ACCESS_TOKEN}@gitlab.com/digital-fo/connectivity/enterprise-connect/predix/ec-px-service.git
  - cd ec-px-service && git clone https://${TOKEN_NAME}:${ACCESS_TOKEN}@gitlab.com/digital-fo/connectivity/enterprise-connect/predix/ec-px-service-assets.git assets
  - git clone https://${TOKEN_NAME}:${ACCESS_TOKEN}@gitlab.com/digital-fo/connectivity/enterprise-connect/predix/ec-px-service-webui.git ec-web-ui && cd ..
  - docker build --build-arg EC_PRVT_KEY=${EC_PRVT_KEY} --build-arg EC_PUB_KEY=${EC_PUB_KEY} -t service .
  - docker run -e PROXY_URL=${PROXY_URL} -e EC_REV=${EC_REV} -e ADMIN_USR=${ADMIN_USR} -e ADMIN_PWD=${ADMIN_PWD} -e ZAC_UAA=${ZAC_UAA} -e ZAC_URL=${ZAC_URL} -e ZAC_SERVICE_ID=${ZAC_SERVICE_ID} -e ZAC_CLIENT_ID=${ZAC_CLIENT_ID} -e ZAC_CLIENT_SECRET=${ZAC_CLIENT_SECRET} -e NUREGO_FEATURE_ID=${NUREGO_FEATURE_ID} -e NUREGO_API_KEY=${NUREGO_API_KEY} -e NR_KEY=${NR_KEY} -e NUREGO_TKN_INS=${NUREGO_TKN_INS} -e NUREGO_TKN_PWD=${NUREGO_TKN_PWD} -e NUREGO_TKN_USR=${NUREGO_TKN_USR} -e NUREGO_USAGE_FEATURE_ID=${NUREGO_USAGE_FEATURE_ID} -e APP=${EC_APP_NAME} -e HOST=${EC_SERVICE_HOST_SUB_DOMAIN} -e NUREGO_ENDPOINT=${NUREGO_ENDPOINT} -e NUREGO_TKN_URL=${NUREGO_TKN_URL} -e EC_PRVT_KEY=${EC_PRVT_KEY} -e EC_PUB_KEY=${EC_PUB_KEY} -e EC_PRVT_PWD=${EC_PRVT_PWD} -e EC_SETTINGS=${EC_SETTINGS} -e VCAP_APPLICATION=${VCAP_APPLICATION} -it enterpriseconnect/service:v1beta

deploy:
  - provider: script
    skip_cleanup: true
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push enterpriseconnect/service:v1beta
    on:
      branch: v1beta_svc_oci_spec

after_deploy: docker rmi enterpriseconnect/service:v1beta -f && docker run -it enterpriseconnect/service:v1beta

notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    - gayatri.tagade@ge.com
    - apolo.yasuda@ge.com
    on_success: always  
    on_failure: always
