language: minimal

services:
  - docker

before_install:
- docker pull enterpriseconnect/agent:v1
- docker images

script:
- docker run -it -d enterpriseconnect/agent:v1 "/root/ecagent_linux_sys -ver"
