language: minimal
if: head_branch = v1.1beta_webportal_oci_spec_update OR branch = v1.1beta_webportal_oci_spec

services:
  - docker
  
before_install:

script:
   - cd ./spec/web-ui && docker build -t enterpriseconnect/webui:v1.1beta --build-arg WEBUI_BRANCH=${WEBUI_BRANCH} .
   
deploy:
  - provider: script
    cleanup: false
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push enterpriseconnect/webui:v1.1beta
    on:
      branch: v1.1beta_webportal_oci_spec

after_deploy: docker rmi enterpriseconnect/webui:v1.1beta -f && docker run -it enterpriseconnect/webui:v1.1beta ./webui -ver

notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    - prasad.alokam@ge.com
    - Simran.Choudhary@ge.com
    - Sheshank.Gujjari@ge.com
    on_success: always  
    on_failure: always
