language: minimal
if: head_branch = v1_oci_spec_update OR branch = v1_oci_spec

services:
  - docker
  
before_install:

script:
   - cd ./spec/agent && docker build -t enterpriseconnect/agent:v1 --build-arg EC_REV_V1=${EC_REV_V1} . && cd -
   - cd ./spec/plugin && docker build -t enterpriseconnect/plugins:v1 --build-arg EC_REV_V1=${EC_REV_V1} . && cd -
   
deploy:
  - provider: script
    skip_cleanup: true
    script: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker push enterpriseconnect/agent:v1
            docker push enterpriseconnect/plugins:v1
    on:
      branch: v1_oci_spec

after_deploy: |
              docker rmi enterpriseconnect/agent:v1 -f && docker run -it enterpriseconnect/agent:v1 agent -ver
              docker rmi enterpriseconnect/plugins:v1 -f && docker run -it enterpriseconnect/plugins:v1 agent -info
              ls -al
  
notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    #- enterprise-connect@ge.com
    on_success: always  
    on_failure: always
