language: minimal
if: head_branch =~ ^v1.2beta_oauth_oci_spec_update$ OR branch = v1.2beta_oauth_oci_spec

services:
  - docker
  
env:
  - HEROKU_APP="ec-oauth-github"
  - HEROKU_REG="registry.heroku.com"
  - EC_REV_V1_2BETA="v1.2beta.reiwa.2"
  - EC_OCI_IMG="enterpriseconnect/oauth:v1.2beta"
  
before_install: >-
  source <(wget -O - https://cli-assets.heroku.com/install-ubuntu.sh) &&
  heroku container:login
  
script:
  - cd ./spec/oauth && docker build -t ${EC_OCI_IMG} --build-arg EC_REV_V1_2BETA=${EC_REV_V1_2BETA} . && cd -
   
deploy:
  - provider: script
    skip_cleanup: true
    script: >-
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
      docker push $EC_OCI_IMG &&
      docker tag enterpriseconnect/oauth:v1.2beta $HEROKU_REG/$HEROKU_APP/web &&
      docker push $HEROKU_REG/$HEROKU_APP/web &&
      heroku container:release web -a $HEROKU_APP
    on:
      branch: v1.2beta_oauth_oci_spec

after_deploy: >-
  docker rmi ${EC_OCI_IMG} -f && docker run -it ${EC_OCI_IMG}
notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    #- enterprise-connect@ge.com
    on_success: always  
    on_failure: always
