language: minimal
if: head_branch =~ ^v1.1beta_helm_pkg_update$ OR branch = v1.1beta_helm_pkg

services:
  - docker
  
before_install:
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

script: 
  - helm version
  - echo $(pwd)
  - eval "sed -i -e 's#<AGENT_HELPER_CHART_REV>#${AGENT_HELPER_CHART_REV}#g' k8s/agent+helper/Chart.yaml"
  - eval "sed -i -e 's#<AGENT_CHART_REV>#${AGENT_CHART_REV}#g' k8s/agent/Chart.yaml"
  - eval "sed -i -e 's#<AGENT_HELPER_CHART_REV>#${AGENT_HELPER_CHART_REV}#g' k8s/agent/Chart.yaml"
  - eval "sed -i -e 's#<AGENT_TLS_CHART_REV>#${AGENT_PLG_CHART_REV}#g' k8s/agent+plg/Chart.yaml"
  - eval "sed -i -e 's#<AGENT_HELPER_CHART_REV>#${AGENT_HELPER_CHART_REV}#g' k8s/example/Chart.yaml"
  - eval "sed -i -e 's#<AGENT_CHART_REV>#${AGENT_CHART_REV}#g' k8s/example/Chart.yaml"
  - cat k8s/agent+helper/Chart.yaml k8s/agent/Chart.yaml k8s/agent+plg/Chart.yaml k8s/example/Chart.yaml
  - mkdir -p k8s/pkg/agent/$AGENT_CHART_REV k8s/pkg/agent+helper/$AGENT_HELPER_REV k8s/pkg/agent+plg/$AGENT_PLG_REV
  - ls -la k8s/pkg
  - helm package k8s/agent+helper -d k8s/pkg/agent+helper/$AGENT_HELPER_CHART_REV
  - helm dependency update k8s/agent
  - helm package k8s/agent -d k8s/pkg/agent/$AGENT_CHART_REV
  - helm package k8s/agent+plg -d k8s/pkg/agent+plg/$AGENT_PLG_CHART_REV
  - echo test example spec
  - helm dependency update k8s/example
  - helm template k8s/example --debug --set-file global.agtConfig=k8s/example/ec.env
  - helm repo index k8s/pkg/agent/$AGENT_CHART_REV --url https://ec-release.github.io/oci/agent/$AGENT_CHART_REV
  - helm repo index k8s/pkg/agent+helper/$AGENT_HELPER_CHART_REV --url https://ec-release.github.io/oci/agent+helper/$AGENT_HELPER_CHART_REV
  - helm repo index k8s/pkg/agent+tls/$AGENT_PLG_CHART_REV --url https://ec-release.github.io/oci/agent+plg/$AGENT_PLG_CHART_REV
  - bash <(wget -O - https://ec-release.github.io/sdk/scripts/agt/v1.1beta.linux64.txt) -inf
  - docker run -it --rm --name=justdatest --env-file=k8s/example/ec.env enterpriseconnect/agent:v1 > agt.log || cat agt.log
  - docker run -it --rm --name=justdatest --env-file=k8s/example/ec.env enterpriseconnect/agent:v1beta > agt.log || cat agt.log
  - docker run -it --rm --name=justdatest --env-file=k8s/example/ec.env enterpriseconnect/plugin:v1 > agt.log || cat agt.log  
  - docker run -it --rm --name=justdatest --env-file=k8s/example/ec.env enterpriseconnect/plugin:v1beta > agt.log || cat agt.log  

after_deploy: chmod 775 ./after_deploy.sh && ./after_deploy.sh

deploy:
  provider: pages 
  github_token: $GITHUB_TOKEN
  local_dir: k8s/pkg
  target_branch: disty
  verbose: true
  skip_cleanup: true
  keep_history: true
  on:
    branch: v1.1beta_helm_pkg

notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    #- enterprise-connect@ge.com
    on_success: always  
    on_failure: always
