language: minimal
if: head_branch =~ ^v1.2beta_oauth_oci_spec_update$ OR branch = v1.2beta_oauth_oci_spec

services:
  - docker
  
#env:
  
before_install: >-
  source <(wget -O - https://cli-assets.heroku.com/install-ubuntu.sh) &&
  heroku container:login
  
script:
  - cd ./spec/oauth && docker build -t enterpriseconnect/oauth:v1.2beta --build-arg EC_REV_V1_2BETA=${EC_REV_V1_2BETA} . && cd -
   
deploy:
  - provider: script
    skip_cleanup: true
    script: >-
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
      docker push enterpriseconnect/oauth:v1.2beta &&
      docker tag enterpriseconnect/oauth:v1.2beta registry.heroku.com/ec-oauth-github/web &&
      docker push registry.heroku.com/ec-oauth-github/web &&
      heroku container:release web
    on:
      branch: v1.2beta_oauth_oci_spec

after_deploy: >-
  docker rmi enterpriseconnect/oauth:v1.2beta -f && docker run -it -e EC_AUTH_VALIDATE=$EC_AUTH_VALIDATE enterpriseconnect/oauth:v1.2beta
notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    #- enterprise-connect@ge.com
    on_success: always  
    on_failure: always
