language: minimal
if: head_branch = v1.1beta_oci_spec_update OR branch = v1.1beta_oci_spec

services:
  - docker
  
before_install:

script:
   - cd ./spec/agent && docker build -t enterpriseconnect/agent:v1.1beta --build-arg EC_REV_V1_1BETA=${EC_REV_V1_1BETA} .
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - provider: script
    script: docker push enterpriseconnect/agent:v1.1beta
    on:
      branch: v1.1beta_oci_spec

after_deploy:

notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    - prasad.alokam@ge.com
    - Simran.Choudhary@ge.com
    - Sheshank.Gujjari@ge.com
    on_success: always  
    on_failure: always
