language: minimal
if: head_branch =~ ^v1_svc_oci_spec_update$ OR branch = v1_svc_oci_spec

services:
  - docker  

env:
  global:
    - SERVICE_BRANCH=v1
    - ENV=v1.kyushu.146
    - EC_REV=v1
    - ADMIN_USR=admin
    - ZAC_UAA=https://predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token
    - ZAC_URL=https://predix-zac.run.aws-usw02-pr.ice.predix.io/v1/authorization/
    - ZAC_SERVICE_ID=enterprise-connect
    - NUREGO_FEATURE_ID=user_login
    - NUREGO_TKN_INS=ins_bf27-2ca0-4594-a2fd-62e6b98bd43d
    - NUREGO_USAGE_FEATURE_ID=api_calls
    - NUREGO_ENDPOINT=https://api.nurego.com/v1
    - NUREGO_TKN_URL=https://api.nurego.com/v1/auth/token

before-script:
  - chmod 775 ./spec/service/envs.sh
    
script:
  - cd ./spec/service
  - docker build --build-arg EC_PRVT_KEY=${EC_PRVT_KEY} --build-arg EC_PUB_KEY=${EC_PUB_KEY} -t enterpriseconnect/service:v1 .
  - source ./envs.sh
  - docker run --rm -d --name service --env-file env.list.sample enterpriseconnect/service:v1 && sleep 10 && docker logs service
  
deploy:
  - provider: script
    skip_cleanup: true
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push enterpriseconnect/service:v1
    on:
      branch: v1_svc_oci_spec

after_deploy: docker rmi enterpriseconnect/service:v1 -f && docker run -it enterpriseconnect/service:v1

notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    - gayatri.tagade@ge.com
    - apolo.yasuda@ge.com
    on_success: always  
    on_failure: always
