language: minimal
if: head_branch =~ ^v1.2_oci_spec_update$ OR branch = v1.2_oci_spec

services:
  - docker

env:
  global:
    - DOCKER_HUB_TAG="enterpriseconnect/agent:v1.2"
    - GITHUB_TAG="ghcr.io/ec-release/oci/agent:v1.2"
    - GITHUB_REGISTRY="https://ghcr.io"
    - GITHUB_USR="ayasuda-ge"
    - DOCKER_USERNAME="apoloyasudadocker"
    - EC_REV_V1_2="1.2-rc.0.reiwa"

before_install:

script:
   - cd ./spec/agent && docker build -t $DOCKER_HUB_TAG --build-arg EC_REV_V1_2=${EC_REV_V1_2} . && cd -
   
deploy:
  - provider: script
    skip_cleanup: true
    script: >-
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin &&
      docker push $DOCKER_HUB_TAG &&
      docker tag $DOCKER_HUB_TAG $GITHUB_TAG &&
      echo $GITHUB_DOCKER_TKN_V1_2 | docker login $GITHUB_REGISTRY -u $GITHUB_USR --password-stdin &&
      docker push $GITHUB_TAG
    on:
      branch: v1.2_oci_spec

after_deploy: >-
  docker rmi $DOCKER_HUB_TAG -f && docker run -it $DOCKER_HUB_TAG -ver
  
notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    #- enterprise-connect@ge.com
    on_success: always  
    on_failure: always
