language: minimal
if: head_branch =~ ^v1beta_svc_oci_spec_update$ OR branch = v1beta_svc_oci_spec

services:
  - docker
  
before_install:

script:
   - cd ./spec/service
   - git clone https://${TOKEN_NAME}:${ACCESS_TOKEN}@gitlab.com/digital-fo/connectivity/enterprise-connect/predix/ec-px-service.git
   - docker build -t enterpriseconnect/service:v1beta --build-arg PROXY_URL=${PROXY_URL} --build-arg ACCESS_TOKEN=${ACCESS_TOKEN} --build-arg CF_USER=${CF_USER} --build-arg CF_PWD=${CF_PWD} --build-arg EC_REV=${EC_REV} --build-arg BUILD_NUMBER=${TRAVIS_BUILD_NUMBER} --build-arg PROJECT_NAME=${PROJECT_NAME} --build-arg ADMIN_USR=${ADMIN_USR} --build-arg ADMIN_PWD=${ADMIN_PWD} --build-arg ZAC_UAA=${ZAC_UAA} --build-arg ZAC_URL=${ZAC_URL} --build-arg ZAC_SERVICE_ID=${ZAC_SERVICE_ID} --build-arg ZAC_CLIENT_ID=${ZAC_CLIENT_ID} --build-arg ZAC_CLIENT_SECRET=${ZAC_CLIENT_SECRET} --build-arg NUREGO_FEATURE_ID=${NUREGO_FEATURE_ID} --build-arg NUREGO_API_KEY=${NUREGO_API_KEY} --build-arg NR_KEY=${NR_KEY} --build-arg NUREGO_TKN_INS=${NUREGO_TKN_INS} --build-arg NUREGO_TKN_PWD=${NUREGO_TKN_PWD} --build-arg NUREGO_TKN_USR=${NUREGO_TKN_USR} --build-arg NUREGO_USAGE_FEATURE_ID=${NUREGO_USAGE_FEATURE_ID} --build-arg EC_APP_NAME=${EC_APP_NAME} --build-arg EC_SERVICE_HOST_SUB_DOMAIN=${EC_SERVICE_HOST_SUB_DOMAIN} --build-arg NUREGO_ENDPOINT=${NUREGO_ENDPOINT} --build-arg NUREGO_TKN_URL=${NUREGO_TKN_URL} .
   
deploy:
  - provider: script
    skip_cleanup: true
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push enterpriseconnect/service:v1beta
    on:
      branch: v1beta_svc_oci_spec

after_deploy: docker rmi enterpriseconnect/service:v1beta -f && docker run -it enterpriseconnect/service:v1beta

notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    - gayatri.tagade@ge.com
    - apolo.yasuda@ge.com
    on_success: always  
    on_failure: always
