language: minimal
if: head_branch = v1_oci_spec_update OR branch = v1_oci_spec

services:
  - docker
  
before_install:

script:
   - cd ./spec/agent && docker build -t enterpriseconnect/agent:v1 --build-arg EC_REV_V1=${EC_REV_V1} .
   
deploy:
  - provider: script
    skip_cleanup: true
    script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push enterpriseconnect/agent:v1
    on:
      branch: v1_oci_spec

after_deploy:

notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    - prasad.alokam@ge.com
    - Simran.Choudhary@ge.com
    - Sheshank.Gujjari@ge.com
    on_success: always  
    on_failure: always
