language: minimal
if: head_branch = v1.1beta_helm_pkg_update

before_install:
  - curl -L https://git.io/get_helm.sh | bash
  - helm init --client-only

script:
  - echo $(pwd)
  - rm -Rf k8s/pkg
  - mkdir -p k8s/pkg/{agent,agent+helper,agent+tls,agent+vln}
  - ls -la k8s/pkg
  - helm package k8s/agent -d k8s/pkg/agent
  - helm package k8s/agent+helper -d k8s/pkg/agent+helper
  - helm package k8s/agent+tls -d k8s/pkg/agent+tls
  - helm package k8s/agent+vln -d k8s/pkg/agent+vln
  - helm repo index k8s/pkg/agent --url https://enterprise-connect.github.io/oci/k8s/pkg/agent/
  - helm repo index k8s/pkg/agent+helper --url https://enterprise-connect.github.io/oci/k8s/pkg/agent+helper/
  - helm repo index k8s/pkg/agent+tls --url https://enterprise-connect.github.io/oci/k8s/pkg/agent+tls/
  - helm repo index k8s/pkg/agent+vln --url https://enterprise-connect.github.io/oci/k8s/pkg/agent+vln/
  
deploy:
  provider: pages 
  github_token: $GITHUB_TOKEN
  local_dir: .
  target_branch: gh-pages
  verbose: true
  skip_cleanup: true
  keep_history: true
  on:
    branch: v1.1beta

script:
  - helm create mychart
  - helm repo add agent https://enterprise-connect.github.io/oci/k8s/pkg/agent/

notifications:  
  email:  
    recipients:  
    - ec-research@ge.com
    - prasad.alokam@ge.com
    - Simran.Choudhary@ge.com
    - Sheshank.Gujjari@ge.com
    on_success: always  
    on_failure: always
