ec-config:
    conf:
      mod: oauth2
      apt: ${EC_PORT}
      dbg: true
      tls: false
    #group to define the authentication method of the connectivity.  
    authGroup:
    - validate: oaep
      scope: ["app.auth","cluster.user"]
      isOwner: false
      privateKey: ${EC_PVTKEY_3}
      publicCrt: ${EC_PUBKEY_3}
      description: "decription #2 for reference only"
  