|!/bin/bash
pwd; ls -al; cat env.list.sample
eval "sed -i -e 's{{EC_PRVT_PWD}}|${EC_PRVT_PWD}|g' env.list.sample"
eval "sed -i -e 's|{{EC_SERVICE_APP}}|${EC_SERVICE_APP}|g' env.list.sample"
eval "sed -i -e 's|{{EC_SERVICE_HOST_SUB_DOMAIN}}|${EC_SERVICE_HOST_SUB_DOMAIN}|g' env.list.sample"
eval "sed -i -e 's|{{EC_SERVICE_ZONE_ID}}|${EC_SERVICE_ZONE_ID}|g' env.list.sample"
eval "sed -i -e 's|{{PROXY_URL}}|${PROXY_URL}|g' env.list.sample"
eval "sed -i -e 's|{{ADMIN_PWD}}|${ADMIN_PWD}|g' env.list.sample"
eval "sed -i -e 's|{{ADMIN_TKN}}|${ADMIN_TKN}|g' env.list.sample"
eval "sed -i -e 's|{{ZAC_UAA}}|${ZAC_UAA}|g' env.list.sample"
eval "sed -i -e 's|{{ZAC_URL}}|${ZAC_URL}|g' env.list.sample"
eval "sed -i -e 's|{{ZAC_SERVICE_ID}}|${ZAC_SERVICE_ID}|g' env.list.sample"
eval "sed -i -e 's|{{ZAC_CLIENT_ID}}|${ZAC_CLIENT_ID}|g' env.list.sample"
eval "sed -i -e 's|{{ZAC_CLIENT_SECRET}}|${ZAC_CLIENT_SECRET}|g' env.list.sample"
eval "sed -i -e 's|{{NUREGO_FEATURE_ID}}|${NUREGO_FEATURE_ID}|g' env.list.sample"
eval "sed -i -e 's|{{NUREGO_API_KEY}}|${NUREGO_API_KEY}|g' env.list.sample"
eval "sed -i -e 's|{{NR_KEY}}|${NR_KEY}|g' env.list.sample"
eval "sed -i -e 's|{{NUREGO_TKN_INS}}|${NUREGO_TKN_INS}|g' env.list.sample"
eval "sed -i -e 's|{{NUREGO_TKN_PWD}}|${NUREGO_TKN_PWD}|g' env.list.sample"
eval "sed -i -e 's|{{NUREGO_TKN_USR}}|${NUREGO_TKN_USR}|g' env.list.sample"
eval "sed -i -e 's|{{NUREGO_USAGE_FEATURE_ID}}|${NUREGO_USAGE_FEATURE_ID}|g' env.list.sample"
eval "sed -i -e 's|{{NUREGO_ENDPOINT}}|${NUREGO_ENDPOINT}|g' env.list.sample"
eval "sed -i -e 's|{{NUREGO_TKN_URL}}|${NUREGO_TKN_URL}|g' env.list.sample"
eval "sed -i -e 's|{{EC_SETTINGS}}|${EC_SETTINGS}|g' env.list.sample"
eval "sed -i -e 's|{{SERVICE_BRANCH}}|${SERVICE_BRANCH}|g' env.list.sample"
eval "sed -i -e 's|{{ENV}}|${ENV}|g' env.list.sample"
eval "sed -i -e 's|{{EC_REV}}|${EC_REV}|g' env.list.sample"
eval "sed -i -e 's|{{ADMIN_USR}}|${ADMIN_USR}|g' env.list.sample
