apiVersion: v1
kind: Pod
metadata:
  name: hello-agt-container-usage
spec:
  restartPolicy: Never
  containers:
    {{- include "agent.plugins" (dict "contrDictContrName" "agtPluginContr" "contrDictReleaseTag" "v1beta" "contrDictSecurityContext" .Values.global.agtK8Config.releaseTag) | nindent 4 }}
    - name: nginx-container
      image: nginx
      command: ["/bin/sh"]
      args: ["-c", "echo Hello from the nginx container"]
    - name: debian-container
      image: debian
      command: ["/bin/sh"]
      args: ["-c", "echo Hello from the debian container"]
