apiVersion: v1
kind: Pod
metadata:
  name: hello_agt_container_usage
spec:
  restartPolicy: Never
  containers:
    {{- include "agent.plugins" (merge (dict "contrDictContrName" "agtPluginContr") .) | nindent 4 }}
    - name: nginx-container
      image: nginx
      command: ["/bin/sh"]
      args: ["-c", "echo Hello from the nginx container"]
    - name: debian-container
      image: debian
      command: ["/bin/sh"]
      args: ["-c", "echo Hello from the debian container"]
