{{- if and (not .Values.global.agtK8Config.withPlugins.vln.remote) (.Values.global.agtK8Config.withPlugins.vln.enabled) -}}
apiVersion: v1
kind: Pod
metadata:
  name: agent-plg-multi-container-usage
spec:
  restartPolicy: Always
  containers:
    {{- include "agent.plugins" (merge (dict "contrDictContrName" "agt-plugin-contr") .) | nindent 4 }}
    - name: busybox-container
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "echo Hello from the busybox container"]
  initContainers:
    - name: busybox-init-container
      # debian image version used 18.09.7
      image: busybox
      # run ip addr cmd to register the ips
      command: ["/bin/sh"]
      securityContext:
        allowPrivilegeEscalation: true
        privileged: true
        # running the priviliged mode w/ the user id INSIDE the container
        runAsUser: 0
        #runAsGroup: 3000
        #fsGroup: 2000
      # to add signle ip to loopback use - ip addr add <ip> dev lo e.g. ip addr add 10.0.1.8 dev lo
      # to add ips with mask use - ip add add <ip>/<mask> dev lo e.g. ip a add 192.168.1.200/24 dev lo
      # to check if ips are added to loopback use command ip addr show
      args: ["-c", "echo Hello from the initial container; sleep 5; ip addr add 10.0.1.8 dev lo; sleep 5; ip a add 192.168.1.200/24 dev lo; sleep 5; ip addr show"]
{{- end -}}
