apiVersion: v1
kind: Pod
metadata:
  name: hello-agt-container-usage
spec:
  restartPolicy: Always
  containers:
    {{- include "agent.plugins" (merge (dict "contrDictContrName" "agt-plugin-contr") .) | nindent 4 }}
    - name: nginx-container
      image: nginx
      command: ["/bin/sh"]
      args: ["-c", "echo Hello from the nginx container"]
  initContainers:
    - name: debian-container
      image: debian
      # run ip addr cmd to register the ips
      command: ["/bin/sh"]
      args: ["-c", "echo Hello from the debian container"]
