apiVersion: v1
entries:
  agent+plg:
  - apiVersion: v1
    appVersion: v1.1beta
    created: "2020-10-13T01:34:42.876264086Z"
    description: The Agent Plugin Helm chart example for Kubernet
    digest: a35acb7ff75741badf1cb2c2ed97de195ef9147383a3cae1373f38063e7593de
    name: agent+plg
    type: application
    urls:
    - https://ec-release.github.io/oci/agent+plg/0.1.2/agent+plg-0.1.2.tgz
    version: 0.1.2
generated: "2020-10-13T01:34:42.873667899Z"
