apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.global.agtK8Config.replicaCount }}
  selector:
    matchLabels:
      {{- include "agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "agent.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "enterpriseconnect/plugin:{{ .Values.global.agtK8Config.releaseTag }}"
          command: {{ include "agent.launchCmd" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- include "agent.portSpec" . | nindent 12 }}
            {{- include "agent.healthPortSpec" . | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.agtK8Config.healthPortName }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.agtK8Config.healthPortName }}
          resources:
            {{- include "agent.podResource" . | nindent 12 }}
          env:
            {{- range (split "\n" .Values.global.agtConfig) }}
            {{- $a := splitn "=" 2 . }}
            {{- if and (not (eq $a._1 "")) ($a._1) }}
            - name: {{ $a._0|quote }}
              value: {{ $a._1|quote }}
            {{- end }}
            {{- end -}}
            {{- $mode := include "agent.mode" . -}}
            {{- $hasPlugin := include "agent.hasPlugin" . -}}
            {{- if (eq $hasPlugin "true") -}}
            {{- if or ((eq $mode "server") (eq $mode "gw:server")) and (.Values.agtK8Config.withPlugins.tls.enabled) -}}
            - name: plg.tlc.scm
              value: {{ .Values.agtK8Config.withPlugins.tls.schema|quote }}
            - name: plg.tlc.hst
              value: {{ .Values.agtK8Config.withPlugins.tls.hostname|quote }}
            - name: plg.tls.prt
              value: {{ .Values.agtK8Config.withPlugins.tls.tlsport|quote }}
            - name: plg.tls.pxy
              value: {{ .Values.agtK8Config.withPlugins.tls.proxy|quote }}
            - name: plg.tls.lpt
              value: {{ .Values.agtK8Config.withPlugins.tls.port|quote }}
            {{- else if or ((eq $mode "client") (eq $mode "gw:client")) and (.Values.agtK8Config.withPlugins.vln.enabled) -}}
            - name: plg.vln.ips
              value: {{ .Values.agtK8Config.withPlugins.vln.ips|quote }}
            {{- end -}}
            {{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
