{{- $agtMode := include "agent.mode" . -}}
{{- if or (eq $agtMode "gateway") (eq $agtMode "gw:client") (eq $agtMode "gw:server") (.Values.global.agtK8Config.withIngress.enabled) -}}
{{- $fullName := include "agent.fullname" . -}}
{{- $svcPort := .Values.global.shared.agtPlugin.agtK8Config.svcPortNum -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
  annotations:
    {}
spec:
  {{- include "agent.ingress" . | nindent 2 }}
{{- end }}
