apiVersion: v1
entries:
  agent:
  - apiVersion: v1
    appVersion: v1.1beta
    created: "2020-07-21T05:05:49.967728766Z"
    description: The Agent Helm chart example for Kubernet
    digest: 7677ae58ad73fde4670b3be48e3701f4602177fd345329b6ef55778480f90d00
    name: agent
    type: application
    urls:
    - https://enterprise-connect.github.io/oci/k8s/pkg/agent/0.1.3/agent-0.1.3.tgz
    version: 0.1.3
generated: "2020-07-21T05:05:49.96674437Z"
