apiVersion: v1
entries:
  agent+helper:
  - apiVersion: v1
    appVersion: 1.16.0
    created: "2020-10-13T01:34:42.837622592Z"
    description: Agent Helm Chart Library
    digest: 771d516d61812c3d6de63081db333159a8bd105775cedc5e75ac16d7eedcc9f3
    name: agent+helper
    type: library
    urls:
    - https://ec-release.github.io/oci/agent+helper/0.1.1/agent+helper-0.1.1.tgz
    version: 0.1.1
generated: "2020-10-13T01:34:42.837240753Z"
