apiVersion: v1
entries:
  agent+plg:
  - apiVersion: v1
    appVersion: v1.1beta
    created: "2020-10-13T19:35:35.84883208Z"
    description: The Agent Plugin Helm chart example for Kubernet
    digest: 4dd95201f5008aac8861f25cfea488455694020191837e059358b9d98c77b3f9
    name: agent+plg
    type: application
    urls:
    - https://ec-release.github.io/oci/agent+plg/0.1.3/agent+plg-0.1.3.tgz
    version: 0.1.3
generated: "2020-10-13T19:35:35.846684291Z"
