apiVersion: v1
entries:
  agent+plg:
  - apiVersion: v1
    appVersion: v1.1beta
    created: "2021-02-10T13:31:12.641253924Z"
    description: The Agent Plugin Helm chart example for Kubernet
    digest: 7b42d74610d95a631b61582bb0b804cafcc17823279a3f4fe9c77fce36e53190
    name: agent+plg
    type: application
    urls:
    - https://ec-release.github.io/oci/agent+plg/0.1.3/agent+plg-0.1.3.tgz
    version: 0.1.3
generated: "2021-02-10T13:31:12.637520833Z"
