apiVersion: v1
entries:
  agent+vln:
  - apiVersion: v1
    appVersion: 1.16.0
    created: "2020-08-06T15:20:07.619153617Z"
    description: A Helm chart for Kubernetes
    digest: 090e992e55929464a488c1a042082998900818b38673bb9a8d11c4d9bfee9612
    name: agent+vln
    type: application
    urls:
    - https://enterprise-connect.github.io/oci/agent+vln/0.1.0/agent+vln-0.1.0.tgz
    version: 0.1.0
generated: "2020-08-06T15:20:07.618287311Z"
