{{- define "agent.conf.tpl" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name | printf "%s-%s" .Chart.Name }}
  data: {}
{{- end -}}
{{- define "agent.conf" -}}
{{- include "agent.conf.merge" (append . "agent.conf.tpl") -}}
{{- end -}}
