{{- define "agent+helper.conf" -}}
{{- include "agent+helper.conf.merge" (append . "agent+helper.conf.tpl") -}}
{{- end -}}
{{- define "agent+helper.conf.tpl" -}}
env:
  {{ range .Files.Lines "conf.env" }}
  {{ $a := splitList "=" . }}
  - name: {{- printf "%s" (index $a 0 ) -}} 
    value: {{- printf "%s" (index $a 1 ) -}}
  {{ end }}
{{- end -}}
